[theme]
base = "light"
primaryColor = "#16a34a"                 # vert (tailwind green-600)
backgroundColor = "#ffffff"              # blanc
secondaryBackgroundColor = "#f6f7f9"     # gris très léger pour les panneaux
textColor = "#0f172a"                    # gris très foncé (lisible)
font = "sans serif"

[client]
toolbarMode = "minimal"                  # moins d’encombrement en haut
