[theme]
base = "light"
primaryColor = "#1463FF"
backgroundColor = "#ffffff"              # blanc
secondaryBackgroundColor = "#F6F8FB"
textColor = "#1F2937"
font = "sans serif"

[client]
toolbarMode = "minimal"                  # moins dâ€™encombrement en haut
